name: Python CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Simulate Deployment
      run: |
        echo "Deploying project..."
        mkdir -p deploy
        cp hello.py deploy/
        echo "Deployment successful!"
